# Generated by Django 4.2.1 on 2023-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_cart_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
