# Generated by Django 4.2.1 on 2023-05-20 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0004_alter_idea_details_alter_idea_name_alter_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='details',
            field=models.TextField(unique=True, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sketch',
            field=models.ImageField(blank=True, null=True, upload_to='sketch_idea', verbose_name='Croquis'),
        ),
        migrations.CreateModel(
            name='RequestIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.CharField(max_length=1000, verbose_name='Résumé')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], help_text='1 : rapide, 2 : moyennement développé, 3 : très développé', max_length=1, verbose_name='Niveau')),
                ('details', models.TextField(unique=True, verbose_name='Détails')),
                ('status', models.BooleanField(default=False, verbose_name='Publié')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas.category', verbose_name='Catégorie')),
                ('thinker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Demande d'idée",
            },
        ),
    ]
