# Generated by Django 4.2.1 on 2023-05-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_idea_date_requestidea_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestidea',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
