# Generated by Django 4.2.1 on 2023-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_idea_details_alter_requestidea_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestidea',
            name='sketch',
            field=models.ImageField(blank=True, null=True, upload_to='sketch_request_idea', verbose_name='Croquis'),
        ),
    ]
