# Generated by Django 4.2.1 on 2023-06-02 07:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0010_requestideacomment_ideacomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea', verbose_name='idée')),
                ('request_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.requestidea', verbose_name="Demande d'idée")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaires idée',
            },
        ),
        migrations.RemoveField(
            model_name='requestideacomment',
            name='request_idea',
        ),
        migrations.RemoveField(
            model_name='requestideacomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='IdeaComment',
        ),
        migrations.DeleteModel(
            name='RequestIdeaComment',
        ),
    ]
