# Generated by Django 4.2.1 on 2023-06-03 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0011_comment_remove_requestideacomment_request_idea_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Commentaire'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='request_idea',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ideas.requestidea', verbose_name="Demande d'idée"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
