# Generated by Django 4.2.1 on 2023-06-04 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_alter_comment_idea_alter_comment_request_idea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'verbose_name': "Idée / Demande d'idée"},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='request_idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.AddField(
            model_name='idea',
            name='request',
            field=models.BooleanField(default=False, help_text="Cocher si c'est une demande d'idée, si c'est une idée (offre) ne pas cocher", verbose_name="Demande d'idée"),
        ),
        migrations.AlterField(
            model_name='comment',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.idea', verbose_name='idée'),
        ),
        migrations.DeleteModel(
            name='RequestIdea',
        ),
    ]
