# Generated by Django 4.2.1 on 2023-06-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_alter_idea_options_remove_comment_request_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Prix'),
        ),
    ]
