# Generated by Django 4.2.1 on 2023-06-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_idea_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='price',
            field=models.FloatField(default=0, verbose_name='Prix'),
        ),
    ]
