# Generated by Django 4.2.1 on 2023-06-05 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0016_alter_idea_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur'),
        ),
        migrations.AddField(
            model_name='idea',
            name='ordered_date',
            field=models.DateField(null=True, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='idea',
            name='thinker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_thinker', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Acheteur')),
                ('ideas', models.ManyToManyField(to='ideas.idea', verbose_name='Idées')),
            ],
            options={
                'verbose_name': 'Panier',
            },
        ),
    ]
