# Generated by Django 4.2.1 on 2023-06-06 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0017_idea_buyer_idea_ordered_date_alter_idea_thinker_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='thinker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
