# Generated by Django 4.2.1 on 2023-06-13 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0018_alter_idea_buyer_alter_idea_thinker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Acheteur'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='ordered_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
    ]
