# Generated by Django 4.2.1 on 2023-05-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_thinker_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinker',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profil', verbose_name='Photo'),
        ),
    ]
