# Generated by Django 4.2.1 on 2023-05-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_thinker_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modérateur',
            },
        ),
    ]
