# Generated by Django 4.2.1 on 2023-06-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinker',
            name='pic',
        ),
    ]
