# Generated by Django 4.2.1 on 2023-06-10 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_thinker_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'adresse")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('line1', models.CharField(max_length=500, verbose_name='Adresse')),
                ('line2', models.CharField(help_text="Num d'appt etc...", max_length=200, verbose_name='Adresse / Complément')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Code postal')),
                ('thinker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
            },
        ),
    ]
