# Generated by Django 4.2.1 on 2023-06-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shippingaddresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddresses',
            new_name='ShippingAddresse',
        ),
    ]
