# Generated by Django 4.2.1 on 2023-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_shippingaddresses_shippingaddresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddresse',
            name='line2',
            field=models.CharField(default='', help_text="Num d'appt etc...", max_length=200, verbose_name='Adresse / Complément'),
        ),
    ]
