# Generated by Django 4.2.1 on 2023-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_shippingaddresse_line2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddresse',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Pays'),
        ),
    ]
