# Generated by Django 4.2.1 on 2023-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_shippingaddresse_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddresse',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
    ]
