# Generated by Django 4.2.1 on 2023-06-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_shippingaddresse_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinker',
            name='stripe_id',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
