# Generated by Django 4.2.1 on 2023-06-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_thinker_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thinker',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
